# -*- coding: utf-8 -*-
"""DecisionTreeClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ht6p_sKWUF59jFDD_dPVbQsK4pok3WK6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('/content/salaries.csv')
data

input = data.drop('salary_more_then_100k', axis =1)
output = data['salary_more_then_100k']
input

output

from sklearn.preprocessing import LabelEncoder
le_C = LabelEncoder()
le_J = LabelEncoder()
le_D = LabelEncoder()

input['company_le'] = le_C.fit_transform(input['company'])
input['job_le'] = le_J.fit_transform(input['job'])
input['degree_le'] = le_D.fit_transform(input['degree'])

input
board = input
board['salary more than 100k'] = output

input

input_le = input.drop(['salary more than 100k', 'company', 'job', 'degree'], axis = 1)
input_le

output

from sklearn.tree import DecisionTreeClassifier
DTC = DecisionTreeClassifier()
model = DTC.fit(input_le, output)

model.predict([[2, 1, 1]])
#Is salary of Google, Computer Programmer, Masters over 100k ?

model.score(input_le, output)

model.predict([[1, 1, 0]])
#Is salary of Facebook, Computer Programmer, Bachelor over 100k ?